// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Chat struct {
	ID           string     `json:"id"`
	Title        string     `json:"title"`
	Members      []*User    `json:"members"`
	MembersCount int        `json:"membersCount"`
	Messages     []*Message `json:"messages"`
	MessageCount int        `json:"messageCount"`
	DateCreated  time.Time  `json:"dateCreated"`
	DateUpdated  time.Time  `json:"dateUpdated"`
}

type CreateChatPayload struct {
	Title string `json:"title"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type JoinChatPayload struct {
	UserID string `json:"userId"`
	ChatID string `json:"chatId"`
}

type Message struct {
	ID          string    `json:"id"`
	Text        string    `json:"text"`
	SenderID    string    `json:"senderId"`
	Sender      *User     `json:"sender"`
	ChatID      string    `json:"chatId"`
	Chat        *Chat     `json:"chat"`
	DateCreated time.Time `json:"dateCreated"`
}

type SendMessageInput struct {
	Text     string `json:"text"`
	SenderID string `json:"senderId"`
	ChatID   string `json:"chatId"`
}

type User struct {
	ID            string    `json:"id"`
	Username      string    `json:"username"`
	MessagesCount int       `json:"messagesCount"`
	DateCreated   time.Time `json:"dateCreated"`
	DateUpdated   time.Time `json:"dateUpdated"`
}
