// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ChatID      uuid.UUID
	Title       string
	DateCreated time.Time
	DateUpdated time.Time
}

type Member struct {
	UserID uuid.UUID
	ChatID uuid.UUID
}

type Message struct {
	MessageID   uuid.UUID
	UserID      uuid.UUID
	ChatID      uuid.UUID
	Content     string
	DateCreated time.Time
}

type User struct {
	UserID      uuid.UUID
	Username    string
	Password    string
	DateCreated time.Time
	DateUpdated time.Time
}
